apiVersion: v1
kind: ServiceAccount
metadata:
  name: openclaw-deployer
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.openclaw-deployer: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"openclaw-deployer"}}'
